development:
 adapter: sqlserver
 database: GS1_New
 host: 162.252.57.64
 username: sa
 password: Zeven123
 port: 2451
 pool: 5
 timeout: 10000000

production:
 adapter: sqlserver
 database: GS1_New
 host: 162.252.57.64
 username: sa
 password: Zeven123
 port: 2451
 pool: 5
 timeout: 10000000

