development:
 adapter: sqlserver
 host: 192.168.1.10  
 database: GS1_New
 username: sa
 password: Gs1vzla
 port: 1433
 pool: 5
 timeout: 5000

production:
 adapter: sqlserver
 database: GS1_New
 host: 192.168.1.10
 username: sa
 password: Gs1vzla
 port: 1433
 pool: 5
 timeout: 5000