Medida.create(codigo: 'KGM', nombre: 'Kilogramo', abreviatura: 'kg')
Medida.create(codigo: 'GRM', nombre: 'Gramo', abreviatura: 'g')
Medida.create(codigo: 'LBR', nombre: 'Libra', abreviatura: 'lb')
Medida.create(codigo: 'MC', nombre: 'Microgramo', abreviatura: 'µg')
Medida.create(codigo: 'MGM', nombre: 'Miligramo', abreviatura: 'mg')
Medida.create(codigo: 'MLT', nombre: 'Mililitro', abreviatura: 'ml')
Medida.create(codigo: 'LTR', nombre: 'Litro', abreviatura: 'L')
Medida.create(codigo: 'ONZ', nombre: 'Onza', abreviatura: 'Oz')
Medida.create(codigo: 'MTQ', nombre: 'Metro cubico', abreviatura: 'm3')
Medida.create(codigo: 'MMQ', nombre: 'Milimetro cubico', abreviatura: 'mm3')
Medida.create(codigo: 'CMQ', nombre: 'Centímetro cúbico', abreviatura: 'cm3')
Medida.create(codigo: 'MMT', nombre: 'Milímetro', abreviatura: 'mm')
Medida.create(codigo: 'MTR', nombre: 'Metro', abreviatura: 'm')
Medida.create(codigo: 'FOT', nombre: 'Pie', abreviatura: 'ft')
Medida.create(codigo: 'INH', nombre: 'Pulgada', abreviatura: 'plg')
Medida.create(codigo: 'KMT', nombre: 'Kilómetro', abreviatura: 'Km')
Medida.create(codigo: 'CMT', nombre: 'Centímetro', abreviatura: 'cm')
Medida.create(codigo: 'CMK', nombre: 'Centimetro cuadrado', abreviatura: 'cm2')
Medida.create(codigo: 'MTK', nombre: 'Metro cuadrado', abreviatura: 'm2')
Medida.create(codigo: 'FTK', nombre: 'Pie cuadrado', abreviatura: 'Pie2')
Medida.create(codigo: 'INK', nombre: 'Pulgada cuadrado', abreviatura: 'plg2')
Medida.create(codigo: 'GLL', nombre: 'Galón (USA)', abreviatura: 'Galón (USA)')
Medida.create(codigo: 'K43', nombre: 'Caballo de fuerza', abreviatura: 'hp')
Medida.create(codigo: 'KWT', nombre: 'Kilowatt', abreviatura: 'kilowatt')
Medida.create(codigo: 'VLT', nombre: 'Voltio', abreviatura: 'Volt')
Medida.create(codigo: 'WTT', nombre: 'Vatio', abreviatura: 'watt')
Medida.create(codigo: 'OHM', nombre: 'Ohm', abreviatura: 'Ohm')
Medida.create(codigo: 'AMP', nombre: 'Amperio', abreviatura: 'Amp')
Medida.create(codigo: 'NIU', nombre: 'Unidades', abreviatura: 'Und')
Medida.create(codigo: 'PTN', nombre: 'Porción', abreviatura: 'Porción')
Medida.create(codigo: 'P1', nombre: 'Porcentaje', abreviatura: 'Porcentaje')
Medida.create(codigo: 'U2', nombre: 'Comprimido', abreviatura: 'Comprimido')
Medida.create(codigo: 'KT', nombre: 'Kit', abreviatura: 'Kit')
Medida.create(codigo: 'E27', nombre: 'Dosis', abreviatura: 'Dosis')
Medida.create(codigo: 'XRO', nombre: 'Rollo', abreviatura: 'Rollo(s)')
Medida.create(codigo: 'H87', nombre: 'Pieza', abreviatura: 'Pieza(s)')
Medida.create(codigo: 'PR', nombre: 'Par', abreviatura: 'Par(es)')
Medida.create(codigo: 'SET', nombre: 'Conjunto', abreviatura: 'Conjunto')



